global:
 scrape_interval: 15s
 external_labels:
  monitor: 'prometheus'

scrape_configs:
 - job_name: 'prometheus'
   static_configs:
     - targets: ['localhost:9100']
     - targets: ['your_web_server_ip:9100']
 - job_name: 'blackbox'
   metrics_path: /probe
   params:
    module: [http_2xx]
   static_configs:
     - targets:
       - http://your_web_server_ip.8080
       - http://your_web_server_ip.5050
   relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: localhost:9115
